name: flask-hello-world

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:

  docker:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_TOKEN}}
        # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
      
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: .
          file: Dockerfile
          builder: ${{steps.buildx.output.name}}
          push: true
          tags: ${{secrets.DOCKER_HUB_USERNAME}}/flask-helloworld
      
      - name: Verify
        run: echo ${{steps.docker_build.outputs.digest}}
